[package]
name = "nano-rs"
version = "0.1.0"
authors = ["michaelk <michael@12ab.pw>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
