// Actions
#[derive(PartialEq)]
pub enum Action {
    AccountBalance,
    AccountBlockCount,
    AccountGet,
    AccountHistory,
    AccountInfo,
    AccountKey,
    AccountRepresentative,
    AccountWeight,
    AccountsBalances,
    AccountsFrontiers,
    AccountsPending,
    ActiveDifficulty,
    AvailableSupply,
    BlockAccount,
    BlockConfirm,
    BlockCount,
    BlockCreate,
    BlockHash,
    BlockInfo,
    Blocks,
    BlocksInfo,
    Bootstrap,
    BootstrapAny,
    BootstrapLazy,
    BootstrapStatus,
    Chain,
    ConfirmationActive,
    ConfirmationHeightCurrentlyProcessing,
    ConfirmationHistory,
    ConfirmationInfo,
    ConfirmationQuorum,
    DatabaseTxnTracker,
    Delegators,
    DelegatorsCount,
    DeterministicKey,
    EpochUpgrade,
    FrontierCount,
    Frontiers,
    Kkeepalive,
    KeyCreate,
    KeyExpand,
    Ledger,
    NodeId,
    NodeIdDelete,
    Peers,
    Pending,
    PendingExists,
    Process,
    Representatives,
    RepresentativesOnline,
    Republish,
    Sign,
    Stats,
    StatsClear,
    Stop,
    Successors,
    Telemetry,
    ValidateAccountNumber,
    Version,
    Unchecked,
    UncheckedClear,
    UncheckedGet,
    UncheckedKeys,
    Unopened,
    Uptime,
    WorkCancel,
    WorkGenerate,
    WorkPeerAdd,
    WorkPeers,
    WorkPeersClear,
    WorkValidate,
}

impl From<&str> for Action {
    pub fn from(action: &str) -> Self {
        match action {
            "account_balance" => Self::AccountBalance,
            "account_block_count" => Self::AccountBlockCount,
            "account_get" => Self::AccountGet,
            "account_history" => Self::AccountHistory,
            "account_info" => Self::AccountInfo,
            "account_key" => Self::AccountKey,
            "account_representative" => Self::AccountRepresentative,
            "account_weight" => Self::AccountWeight,
            "accounts_balances" => Self::AccountsBalances,
            "accounts_frontiers" => Self::AccountsFrontiers,
            "accounts_pending" => Self::AccountsPending,
            "active_difficulty" => Self::ActiveDifficulty,
            "available_supply" => Self::AvailableSupply,
            "block_account" => Self::BlockAccount,
            "block_confirm" => Self::BlockConfirm,
            "block_count" => Self::BlockCount,
            "block_create" => Self::BlockCreate,
            "block_hash" => Self::BlockHash,
            "block_info" => Self::BlockInfo,
            "blocks" => Self::Blocks,
            "blocks_info" => Self::BlocksInfo,
            "bootstrap" => Self::Bootstrap,
            "bootstrap_any" => Self::BootstrapAny,
            "bootstrap_lazy" => Self::BootstrapLazy,
            "bootstrap_status" => Self::BootstrapStatus,
            "chain" => Self::Chain,
            "confirmation_active" => Self::ConfirmationActive,
            "confirmation_height_currently_processing" => Self::ConfirmationHeightCurrentlyProcessing,
            "confirmation_history" => Self::ConfirmationHistory,
            "confirmation_info" => Self::ConfirmationInfo,
            "confirmation_quorum" => Self::ConfirmationQuorum,
            "database_txn_tracker" => Self::DatabaseTxnTracker,
            "delegators" => Self::Delegators,
            "delegators_count" => Self::DelegatorsCount,
            "deterministic_key" => Self::DeterministicKey,
            "epoch_upgrade" => Self::EpochUpgrade,
            "frontier_count" => Self::FrontierCount,
            "frontiers" => Self::Frontiers,
            "keepalive" => Self::Kkeepalive,
            "key_create" => Self::KeyCreate,
            "key_expand" => Self::KeyExpand,
            "ledger" => Self::Ledger,
            "node_id" => Self::NodeId,
            "node_id_delete" => Self::NodeIdDelete,
            "peers" => Self::Peers,
            "pending" => Self::Pending,
            "pending_exists" => Self::PendingExists,
            "process" => Self::Process,
            "representatives" => Self::Representatives,
            "representatives_online" => Self::RepresentativesOnline,
            "republish" => Self::Republish,
            "sign" => Self::Sign,
            "stats" => Self::Stats,
            "stats_clear" => Self::StatsClear,
            "stop" => Self::Stop,
            "successors" => Self::Successors,
            "telemetry" => Self::Telemetry,
            "validate_account_number" => Self::ValidateAccountNumber,
            "version" => Self::Version,
            "unchecked" => Self::Unchecked,
            "unchecked_clear" => Self::UncheckedClear,
            "unchecked_get" => Self::UncheckedGet,
            "unchecked_keys" => Self::UncheckedKeys,
            "unopened" => Self::Unopened,
            "uptime" => Self::Uptime,
            "work_cancel" => Self::WorkCancel,
            "work_generate" => Self::WorkGenerate,
            "work_peer_add" => Self::WorkPeerAdd,
            "work_peers" => Self::WorkPeers,
            "work_peers_clear" => Self::WorkPeersClear,
            "work_validate" => Self::WorkValidate,
        }
    }
}